[server_assignment]
players.maximum = 4096
players.preferred = 666
instances.count = 1

[game_setup]
# Aliases for "v348" is "2018M", "v463" is "2021E", etc.
roblox_version = '2021E'
place_path = 'C:\Users\USERNAME\Documents\AmusementPark.rbxl'
icon_path = 'C:\Users\USERNAME\Pictures\097050bd37142a4080975bb8e415d2b8.jpg'
name = ''
description = ''
creator.name = 'Ã’Ã“'

[server_core]
chat_style = 'ClassicAndBubble'

retrieve_default_user_code = '''
def RESULT(tick: float) -> str:
    return f'Tick {tick}'
'''

retrieve_username = '''
def RESULT(user_code: str) -> str:
    import datetime
    return datetime.datetime.fromtimestamp(float(user_code[5:])).strftime('%H:%M:%S')
'''

retrieve_user_id = '''
def RESULT(user_code: str) -> int:
    return int(float(user_code[5:]) % 1e3)
'''

retrieve_account_age = '''
def RESULT(user_code: str) -> int:
    return 6969
'''
